#/control/verbose 1
/run/verbose 1
/process/em/verbose 0
/process/had/verbose 0
/tracking/verbose 0
/event/verbose 0

/scinsm/setSurfaceRoughness 0.999
/scinsm/setClad1Radius 0.3 mm
/scinsm/setClad2Radius 0.1 mm
/scinsm/setMPPCHalfLength 0.6 mm
/scinsm/setGap 0.15 mm
/scinsm/setAlignment 0.1 deg
/scinsm/setCoatingThickness 0.3 mm
/scinsm/setCoatingRadius 1.775 mm

/run/initialize
#/vis/disable
/gps/particle mu-

/gps/energy 24 MeV

/gps/position 0 3 0 cm
/gps/direction 0 -1 0
/run/beamOn 9000
#/run/initialize
